### ISSUE TITLE
BlueTooth enabled?

### ISSUE THREAD

**Issue by TheBelgarion** [generaliinformatik/mycoradar#2]
Im not sure why you would need BlueTooth?
I wanted to run a Test in Bluestacks Android Emulator which doesnt Support BlueTooth anyway so i always gets stuck at "turn BlueTooth on"

Apps should not request permissions to things they don't need in my opinion, or do you need use it for tracking proximity? Can't see that from the chart?

**Comment by dehesselle** [comment]
Did you take a look at the code? A quick grep reveals that it uses Bluetooth.

It should be mentioned in the readme, though.

**Comment by TheBelgarion** [comment]
did not check the whole code base and as you said readme does not say anything about how its done.

**Comment by rfuehrer** [comment]
@TheBelgarion:

Sorry for the late feedback. Thanks to René dH you got feedback. the readme is not complete yet, because the hackathon was very ambitious - we worked until the last minute to develop a runnable prototype. unfortunately, as often happens, the documentation was missed out.

But we'll make up for that in the next few days. thanks for your advice.
